//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluentify {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DescriptorAttributeAnalyzer_Resources {
        
        private static global::System.Resources.ResourceManager _resourceMan;

        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptorAttributeAnalyzer_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fluentify.DescriptorAttributeAnalyzer.Resources", typeof(DescriptorAttributeAnalyzer_Resources).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is marked with the Ignore attribute, removing it from consideration by Fluentify, making use of the Descriptor attribute redundant..
        /// </summary>
        internal static string DisregardedRuleDescription {
            get {
                return ResourceManager.GetString("DisregardedRuleDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is marked with the Ignore attribute, removing it from consideration by Fluentify..
        /// </summary>
        internal static string DisregardedRuleMessageFormat {
            get {
                return ResourceManager.GetString("DisregardedRuleMessageFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor is disregarded from consideration by Fluentify.
        /// </summary>
        internal static string DisregardedRuleTitle {
            get {
                return ResourceManager.GetString("DisregardedRuleTitle", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property and its Descriptor are not considered by Fluentify because the type has not been annotated with the Fluentify attribute..
        /// </summary>
        internal static string MissingFluentifyRuleDescription {
            get {
                return ResourceManager.GetString("MissingFluentifyRuleDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor for Property &apos;{0}&apos; will not be applied - &apos;{1}&apos; is not annotated with Fluentify..
        /// </summary>
        internal static string MissingFluentifyRuleMessageFormat {
            get {
                return ResourceManager.GetString("MissingFluentifyRuleMessageFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type does not utilize Fluentify.
        /// </summary>
        internal static string MissingFluentifyRuleTitle {
            get {
                return ResourceManager.GetString("MissingFluentifyRuleTitle", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Descriptor for the Property matches the default value applied by Fluentify, making use of the Descriptor attribute redundant..
        /// </summary>
        internal static string RedundantRuleDescription {
            get {
                return ResourceManager.GetString("RedundantRuleDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor &apos;{0}&apos; for Property &apos;{1}&apos; is Redundant - Fluentify already applies this descriptor by default..
        /// </summary>
        internal static string RedundantRuleMessageFormat {
            get {
                return ResourceManager.GetString("RedundantRuleMessageFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified descriptor is already the default used by Fluentify.
        /// </summary>
        internal static string RedundantRuleTitle {
            get {
                return ResourceManager.GetString("RedundantRuleTitle", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value provided for the Descriptor will be used as the name of the extension method and must adhere to the standard C# .NET naming conventions for methods..
        /// </summary>
        internal static string ValidNamingRuleDescription {
            get {
                return ResourceManager.GetString("ValidNamingRuleDescription", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not suitable for use as an extension method name..
        /// </summary>
        internal static string ValidNamingRuleMessageFormat {
            get {
                return ResourceManager.GetString("ValidNamingRuleMessageFormat", _resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor must adhere to the naming conventions for Methods.
        /// </summary>
        internal static string ValidNamingRuleTitle {
            get {
                return ResourceManager.GetString("ValidNamingRuleTitle", _resourceCulture);
            }
        }
    }
}
