//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluentify {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NullabilityAttributeAnalyzer_Resources {

        private static global::System.Resources.ResourceManager _resourceMan;

        private static global::System.Globalization.CultureInfo _resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NullabilityAttributeAnalyzer_Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fluentify.NullabilityAttributeAnalyzer.Resources", typeof(NullabilityAttributeAnalyzer_Resources).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AllowNull is redundant on nullable properties because generated Fluentify extensions already allow null assignments for nullable properties..
        /// </summary>
        internal static string RedundantAllowNullRuleDescription {
            get {
                return ResourceManager.GetString("RedundantAllowNullRuleDescription", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is nullable, making the usage of the AllowNull attribute redundant..
        /// </summary>
        internal static string RedundantAllowNullRuleMessageFormat {
            get {
                return ResourceManager.GetString("RedundantAllowNullRuleMessageFormat", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AllowNull is redundant for nullable properties.
        /// </summary>
        internal static string RedundantAllowNullRuleTitle {
            get {
                return ResourceManager.GetString("RedundantAllowNullRuleTitle", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DisallowNull is redundant on non-nullable properties because generated Fluentify extensions already reject null assignments for non-nullable properties..
        /// </summary>
        internal static string RedundantDisallowNullRuleDescription {
            get {
                return ResourceManager.GetString("RedundantDisallowNullRuleDescription", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not nullable, making the usage of the DisallowNull attribute redundant..
        /// </summary>
        internal static string RedundantDisallowNullRuleMessageFormat {
            get {
                return ResourceManager.GetString("RedundantDisallowNullRuleMessageFormat", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DisallowNull is redundant for non-nullable properties.
        /// </summary>
        internal static string RedundantDisallowNullRuleTitle {
            get {
                return ResourceManager.GetString("RedundantDisallowNullRuleTitle", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MaybeNull is redundant on nullable properties because generated Fluentify extensions already allow null assignments for nullable properties..
        /// </summary>
        internal static string RedundantMaybeNullRuleDescription {
            get {
                return ResourceManager.GetString("RedundantMaybeNullRuleDescription", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is nullable, making the usage of the MaybeNull attribute redundant..
        /// </summary>
        internal static string RedundantMaybeNullRuleMessageFormat {
            get {
                return ResourceManager.GetString("RedundantMaybeNullRuleMessageFormat", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MaybeNull is redundant for nullable properties.
        /// </summary>
        internal static string RedundantMaybeNullRuleTitle {
            get {
                return ResourceManager.GetString("RedundantMaybeNullRuleTitle", _resourceCulture);
            }
        }
    }
}