//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluentify {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecordAnalyzer_Resources {

        private static global::System.Resources.ResourceManager _resourceMan;

        private static global::System.Globalization.CultureInfo _resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecordAnalyzer_Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fluentify.RecordAnalyzer.Resources", typeof(RecordAnalyzer_Resources).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Records with the Fluentify attribute must be partial when Fluentify needs to generate a parameterless constructor..
        /// </summary>
        internal static string PartialRecordRequiredRuleDescription {
            get {
                return ResourceManager.GetString("PartialRecordRequiredRuleDescription", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record &apos;{0}&apos; has the Fluentify attribute but is not partial; add the partial modifier so Fluentify can create a parameterless constructor..
        /// </summary>
        internal static string PartialRecordRequiredRuleMessageFormat {
            get {
                return ResourceManager.GetString("PartialRecordRequiredRuleMessageFormat", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record must be partial to allow Fluentify to generate a parameterless constructor.
        /// </summary>
        internal static string PartialRecordRequiredRuleTitle {
            get {
                return ResourceManager.GetString("PartialRecordRequiredRuleTitle", _resourceCulture);
            }
        }
    }
}
