//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluentify {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SkipAutoInitializationAttributeAnalyzer_Resources {

        private static global::System.Resources.ResourceManager _resourceMan;

        private static global::System.Globalization.CultureInfo _resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SkipAutoInitializationAttributeAnalyzer_Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fluentify.SkipAutoInitializationAttributeAnalyzer.Resources", typeof(SkipAutoInitializationAttributeAnalyzer_Resources).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SkipAutoInitialization takes precedence over AutoInitiateWith when applied to the same type. Remove AutoInitiateWith to avoid confusion..
        /// </summary>
        internal static string ConflictingAttributesRuleDescription {
            get {
                return ResourceManager.GetString("ConflictingAttributesRuleDescription", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AutoInitiateWith on &apos;{0}&apos; will be ignored because SkipAutoInitialization is also applied..
        /// </summary>
        internal static string ConflictingAttributesRuleMessageFormat {
            get {
                return ResourceManager.GetString("ConflictingAttributesRuleMessageFormat", _resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AutoInitiateWith ignored when SkipAutoInitialization is present.
        /// </summary>
        internal static string ConflictingAttributesRuleTitle {
            get {
                return ResourceManager.GetString("ConflictingAttributesRuleTitle", _resourceCulture);
            }
        }
    }
}
